### ISSUE TITLE
Feedback for "Architectural Overview"

### ISSUE THREAD

**Issue by MichaelPShea** [SAP-docs/btp-business-application-studio#1]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/c93afb5743a04b62afea0fe1def00062.html

If you view the graphic in github in dark mode, the graphic does not work.

**Comment by MichaelPShea** [comment]
![image](https://user-images.githubusercontent.com/25907918/118613608-32920900-b7bf-11eb-8f1d-5aafbd982c26.png)

**Comment by Paolaufer** [comment]
Hi Michael,
Thank you for your feedback!
I have updated the graphic and now it is visible inthe dark theme too.

![image](https://user-images.githubusercontent.com/26144308/118811647-ed043780-b8b5-11eb-9fba-cf298b4f6d07.png)

**Comment by je-hal** [comment]
@MichaelPShea : Does this solve the issue from your point of view?
