### ISSUE TITLE
Feedback for "Creating a Project from the Terminal"

### ISSUE THREAD

**Issue by iwonahahn** [SAP-docs/btp-business-application-studio#10]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/c29e1a3a652242e089af453c2177249a.html?locale=en-US

In Markdown it looks good:

![image](https://user-images.githubusercontent.com/22098308/119866987-aea5f280-bf1d-11eb-9748-d06a7b83790b.png)

but not on SAP Help Portal:

![image](https://user-images.githubusercontent.com/22098308/119866941-a2219a00-bf1d-11eb-8af7-91458063cd20.png)

**Comment by greg2git** [comment]
while at it, why not mention the shortcut:
**CTRL+`** 
it works better on the US keyboard than it reads as an instruction since it can easily be confused with:
**CTRL+'** 
which does 'nothing'.

**Comment by Paolaufer** [comment]
Hi,
Thank you both for your feedback!

@iwonahahn There is already an internal thread open with this issue. You are welcome to follow the progress there,  https://sapjira.wdf.sap.corp/browse/DPS-11558

@greg2git  We prefer not to confuse the users with several ways of doing the same action, so for the moment we will keep the menu instructions.  For the users who prefer to use the keyboard, there is a link to the list of the shortcuts on the SAP Business Application Studio **Welcome** page.
