### ISSUE TITLE
Feedback for "Connecting to External Systems" - Broken tutorial link

### ISSUE THREAD

**Issue by Shegox** [SAP-docs/btp-business-application-studio#107]
The link at the bottom of the page is broken and points to a no longer existing tutorial (https://developers.sap.com/tutorials/cp-connectivity-install-cloud-connector.html). I wasn't able to find an updated link for this specific tutorial.

>  If you don't have any Cloud Connector to use, you can set up a Cloud Connector on your local machine/VM by following [this tutorial](https://developers.sap.com/tutorials/cp-connectivity-install-cloud-connector.html).

Source: https://github.com/SAP-docs/btp-business-application-studio/blob/587abea7fda99e5bef2ad965fe2da19ea6d5ff75/docs/Connecting_to_External_Systems_7e49887.md?plain=1#L159

---

https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/7e49887e6fd34182bebeca5a6841a0cc.html?locale=en-US

**Comment by Paolaufer** [comment]
Thank you for bringing this to our attention!
I will update the documentation accordingly.
