### ISSUE TITLE
Feedback for "Getting Started with a Trial Account"

### ISSUE THREAD

**Issue by iwonahahn** [SAP-docs/btp-business-application-studio#11]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/48ed55ec07e04a02b2218236c336321b.html?locale=en-US

On Trial users can access SAP Business Application Studio via Quick Tool Access.

**Comment by Paolaufer** [comment]
Hi @iwonahahn,
Thank you for your feedback.
I will update the document with the reference to the Quick Tool Access.
You will see the changes on our next release.

**Comment by iwonahahn** [comment]
https://people.sap.com/iwona.hahn
