### ISSUE TITLE
Feedback for "What is SAP Business Application Studio?"

### ISSUE THREAD

**Issue by marckuipers** [SAP-docs/btp-business-application-studio#110]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/8f46c6e6f86641cc900871c903761fd4.html?locale=en-US&version=Cloud

Test

**Comment by Paolaufer** [comment]
Hi,
I hope the test worked :)
I'm closing the issue.
Reopen if there is still an AI.
