### ISSUE TITLE
Feedback for "Working in the Dev Space Manager"

### ISSUE THREAD

**Issue by edwin7** [SAP-docs/btp-business-application-studio#112]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/ad40d52d0bea4d79baaf9626509caf33.html?locale=en-US

A screenshot where to find "Upload Files" option during import process would be helpful. It was hard to be seen because it is at the bottom of the menu.

**Comment by Paolaufer** [comment]
Hi, 
Do you mean a screenshot of the open File menu?

**Comment by edwin7** [comment]
To upload files

**Comment by Paolaufer** [comment]
Hi,
You need to open the File menu to upload files.  
![image](https://user-images.githubusercontent.com/26144308/139702913-1a1a7934-9162-49e4-bbd2-2e84301acc5b.png)
Is this helpful?

**Comment by edwin7** [comment]
Yes Paola.
I couldn't find the option easily somehow. That is why I suggest to add the screenshot in the doc. Just personal opinion.

**Comment by Paolaufer** [comment]
Thank you for bringing this to our attention. I will keep this in mind. If we get any more feedback about this, I will add a screenshot.
