### ISSUE TITLE
Feedback for "Restrictions"

### ISSUE THREAD

**Issue by ag3silaus** [SAP-docs/btp-business-application-studio#113]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/a45742a719704bdea179b4c4f9afa07f.html?locale=en-US

Hello Experts,

Although it says "The maximum size limit of a dev space is 4 GB" in the list, my dev space is already 8 gb. Also, when I click on the restriction link in Business Application Studio, I am directed to the main page, not the Restriction page.
Also, I contributed with the PR before, but I did not receive my badge.
Have a nice day

![dspace](https://user-images.githubusercontent.com/58527608/139209623-45f34271-d3dc-40c4-bd95-401e63c3c9d1.PNG)
,

**Comment by Paolaufer** [comment]
Hi,
We will update the link soon! Thank you for pointing this out!
If it helps, this is the link: https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/a45742a719704bdea179b4c4f9afa07f.html

As per the disk space, please let me know if you are talking about a new dev space you created in the Trial environment.
If the limitation was established after the dev space creation, then you will still get the previous size allowance. 

Badges are allotted once a week. If you still have not received yours, let me know and I will look into it.

**Comment by ag3silaus** [comment]
> Thank you for your valuable feedback contribution, @ag3silaus! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/ag3silaus

**Comment by ag3silaus** [comment]
> Hi, We will update the link soon! Thank you for pointing this out! If it helps, this is the link: https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/a45742a719704bdea179b4c4f9afa07f.html
> 
> As per the disk space, please let me know if you are talking about a new dev space you created in the Trial environment. If the limitation was established after the dev space creation, then you will still get the previous size allowance.
> 
> Badges are allotted once a week. If you still have not received yours, let me know and I will look into it.

Hi @Paolaufer,
I think I created my first devspace before the restrictions, Then I must try not to delete :D
https://github.com/SAP-docs/btp-business-application-studio/pull/105 this was my PR which is one two weeks ago.
Regards 
Burak

**Comment by Paolaufer** [comment]
@qmacro could you please take a look to see why Burak did not get his badge for his contribution?

**Comment by Paolaufer** [comment]
You will receive your badge soon. I'm closing the item. If you have not gotten your badge in a couple of days, please open a new one for that so I can follow up.

**Comment by qmacro** [comment]
Hi @ag3silaus   - badge assignment is now on its way, my apologies - it's my fault the system is a little slow.

**Comment by ag3silaus** [comment]
> Hi @ag3silaus - badge assignment is now on its way, my apologies - it's my fault the system is a little slow.

Hi DJ @qmacro, thank you for your time.
