### ISSUE TITLE
Feedback for "What's New for SAP Business Application Studio"

### ISSUE THREAD

**Issue by f4abap** [SAP-docs/btp-business-application-studio#114]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/ed631d4ee2214e9f932b03d40b2c7e41.html?locale=en-US

If I hit edit it has a dead end. 

What I also want to ask if the coumn deploy to ABAP is the correct wording. Shouldn't it named deploy to Netweaver Stack?

**Comment by Paolaufer** [comment]
Hi,
We go with the term Deploy to ABAP. 
As per the what;s new edit link, I will look into it. Thank you for letting us know!!!

**Comment by Paolaufer** [comment]
The Edit button issue has been fixed.
