### ISSUE TITLE
Add shortcut keys for command palette 

### ISSUE THREAD

**Issue by KushagraTandon02** [SAP-docs/btp-business-application-studio#115]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/ba59cb69245443008d016690fd068fcf.html?locale=en-US&version=Cloud

We can add shortcut keys for VSCode Command Palette(Ctrl+shift+P) for new users to know and easily interact with new development environment.

**Comment by Paolaufer** [comment]
Hi,
Could you please be more specific?
Are you asking us to add the shortcut for opening up the Command Palette?

**Comment by KushagraTandon02** [comment]
Yeah! we can add shortcut keys for these. Like shown over in tutorial Step 8
[https://developers.sap.com/tutorials/btp-app-set-up-local-development.html](url)

**Comment by ShiraManas** [comment]
Great idea! I have added the keyboard shortcut to the topic and it should appear with our next release. Thanks for your feedback!

**Comment by KushagraTandon02** [comment]
https://people.sap.com/kushagratandon
