### ISSUE TITLE
Feedback for "SAP Mobile Application"

### ISSUE THREAD

**Issue by jitendrakansal** [SAP-docs/btp-business-application-studio#12]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/95f86cceb6f1441d81c2b562766719ed.html?locale=en-US&version=Cloud

Regarding **Mobile Development Kit** reference, updated cotent is available at this page https://help.sap.com/doc/f53c64b93e5140918d676b927a3cd65b/Cloud/en-US/docs-en/guides/getting-started/mdk/bas.html

**Comment by Paolaufer** [comment]
Hi,
Thank you for the update. I have changed the link to the one you provided.
You will be able to see the new link with our next release.

**Comment by jitendrakansal** [comment]
https://people.sap.com/jitendrakumar.kansal
