### ISSUE TITLE
Feedback for "Terminal"

### ISSUE THREAD

**Issue by raeijpe** [SAP-docs/btp-business-application-studio#123]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/c8b4ae95701942a5a21be4e84749f97f.html?locale=en-US

Not everybody is familiar with linux command-line. Maybe it is an idea to add a link or section with most used commands and a explanation.

**Comment by ShiraManas** [comment]
Hi. This is a great idea! Is this link helpful? https://hackr.io/blog/basic-linux-commands
Or do you have another resource to recommend that I can link to with the most used commands of linux command-line?
Which commands are most useful in the terminal?

**Comment by Paolaufer** [comment]
Hi,
The terminal option is given for developers who prefer it.
There are UI options for those less familiar.
