### ISSUE TITLE
Feedback for "Service Center"

### ISSUE THREAD

**Issue by raeijpe** [SAP-docs/btp-business-application-studio#124]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/1e8ec75c9c784b51a91c7370f269ff98.html?locale=en-US

In the documentation is mentioned:
 or select View  Service Center from the menu bar.

This should be
 or select View -> Open View -> Service Center from the menu bar.

**Comment by ShiraManas** [comment]
You're right! It seems that the UI was changed. I will update this in the documentation and the change should appear in our next release (a week and a half from now). Thanks for pointing that out.

**Comment by raeijpe** [comment]
https://people.sap.com/r.eijpe
