### ISSUE TITLE
Feedback for "Creating a Project from the Terminal"

### ISSUE THREAD

**Issue by jrbpraven** [SAP-docs/btp-business-application-studio#125]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/c29e1a3a652242e089af453c2177249a.html?locale=en-US

Hi, I was watching the content of this documentation and I think it's important to know there is the alternative to use the terminal to create Fiori projects via templates, but I think too the way this alternative is showed it's kind of empty. I think maybe you can add some existing resourse maybe on developers.sap.com (in some tutorial). So, the person how read this has a clear example how to do that and you won't include much more detail in the offical documentation of SAP BAS. What do you think about this idea?

**Comment by ShiraManas** [comment]
Hi! We have another topic about creating projects from the [Template Wizard](https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/ba59cb69245443008d016690fd068fcf.html?locale=en-US&version=Cloud) in the BAS documentation. 
Are you suggesting to add a related link to the end of the command palette/template wizard topic to show how to create a Fiori Project? Maybe we can add a link to this topic: [Generate an Application](https://help.sap.com/viewer/17d50220bcd848aa854c9c182d65b699/Latest/en-US/db44d45051794d778f1dd50def0fa267.html) from the Fiori tools documentation.
Is this what you had in mind?
We also have this tutorial that can be added as a related link for the command palette topic: [Create an SAP Fiori App Using SAP Business Application Studio](https://developers.sap.com/tutorials/appstudio-fioriapps-create.html). What do you think?
Thanks for your feedback!

**Comment by jrbpraven** [comment]
Hi Shira, I think the alternatives you gave me are so good, but my original message was refered to the alternative to create apps by using command line. So I think the tutorial [Create an SAPUI5 App from the Command Line](https://developers.sap.com/tutorials/cp-cf-sapui5-local.html) is good way to show step by step. My idea was, add this kind of existing resource in the official documentation, not as a content but as a reference instead.
It's only a suggesttion, maybe is usefull for someone in the community.

**Comment by ShiraManas** [comment]
This is great feedback! I have added the link to the tutorial that you sent to the topic. It will appear with our next release. Thank you!

**Comment by jrbpraven** [comment]
https://people.sap.com/josereynaldo.bautistapalomino
