### ISSUE TITLE
Feedback for "Connecting to a Corporate Git Repository"

### ISSUE THREAD

**Issue by ckulka** [SAP-docs/btp-business-application-studio#129]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/d54ddfc1bc4f45b19dabfa0950799685.html?locale=en-US&version=Cloud

We followed the guide the other day, but ran into `Received HTTP code 502 from proxy after CONNECT` errors when trying to clone a repository in BAS after the setup was done.

It turned out that when BAS is already up and running **before** the Cloud Connector and Destination setup is completed, the new proxy settings aren't propagated to the BAS instance. A manual refresh of the proxy settings fixes it though.

I'd propose adding a note along the lines of:

> If BAS was already up and running before you started with this guide, you might get a `Received HTTP code 502 from proxy after CONNECT` error when cloning a repository.
> 
> If that's the case, open a new terminal in BAS (_Terminal_ &raquo; _New Terminal_) and execute `curl http://localhost:8887/reload`.
> 
> This will reload the new proxy configuration in your BAS instance and you should now be able to clone the repository.

I will also submit a PR if this proposal makes sense.

**Comment by Paolaufer** [comment]
Hi, 
Thank you for your feedback. I will add your solution to our Guided Answers and also add a prerequisite to this procedure to set the Cloud Connector and destination before they start.
