### ISSUE TITLE
Feedback for "Subscribe to SAP Business Application Studio" - Link to Pricing and Packaging results in 404 page

### ISSUE THREAD

**Issue by abap-weasel** [SAP-docs/btp-business-application-studio#132]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/6331319fd9ea4f0ea5331e21df329539.html?locale=en-US&version=Cloud

URL links to
https://help.sap.com/docs/link-disclaimer?site=https%3A%2F%2Fwww.sap.com%2Fproducts%2Fcloud-platform%2Fpricing.html
results in 
Sorry, this page can’t be found.
Please search SAP.com or browse the links below.

**Comment by Paolaufer** [comment]
Thank you for bringing thsi to my attention. Will update the link now.

**Comment by abap-weasel** [comment]
@Paolaufer : The issue was closed, although the link is still not working. Can you re-check. please?

**Comment by Paolaufer** [comment]
@abap-weasel The link should be working now.
