### ISSUE TITLE
Feedback for "Subscribe to SAP Business Application Studio" - Details on required quota / entitlement

### ISSUE THREAD

**Issue by abap-weasel** [SAP-docs/btp-business-application-studio#133]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/6331319fd9ea4f0ea5331e21df329539.html?locale=en-US&version=Cloud

Doc says this "Note
If you don't see the SAP Business Application Studio tile in the results, check the entitlement configuration for your subaccount. See [Configure Entitlements and Quotas for Subaccounts](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/5ba357b4fa1e4de4b9fcc4ae771609da.html)." and links to a general guide on what are entitlement and quotas, but there is no information what quota / or entitlement is required. Please add that information.

**Comment by ShiraManas** [comment]
Thanks for your feedback! I agree that the information about which entitlement is required should be added.
I have updated the note to include information about the required entitlement and the change should appear with our next release.

Note: If you don't see the SAP Business Application Studio tile in the results, make sure that there's an entitlement for SAP Business Application Studio in your subaccount. See Configure Entitlements and Quotas for Subaccounts.
