### ISSUE TITLE
Feedback for "Creating a Project Using the Wizard"

### ISSUE THREAD

**Issue by Paolaufer** [SAP-docs/btp-business-application-studio#136]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/75ff48052e0e4c7dad0cbcf6a69c57ee.html

- Add that you need to go to the hamburger to get to the File menu
- Ask Liat or Yuval if number 3 is still relevant.

**Comment by ShiraManas** [comment]
Updated #3: The project is added to your dev space in a new workspace or as part or a multi-root workspace depending on the Workspace preferences that you defined.
Added From the left-side menu, select File...
