### ISSUE TITLE
Feedback for "Creating a Project from the Terminal"

### ISSUE THREAD

**Issue by Paolaufer** [SAP-docs/btp-business-application-studio#137]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/c29e1a3a652242e089af453c2177249a.htm

Also say to open the hamburger to get to the Terminal menu, and check that it works. 
l was asked for which project I want to open the terminal, so I am agraid I opened a project within a project, but I can;t see oit.

**Comment by ShiraManas** [comment]
Hi. This worked for me perfectly as is. I don't know if we need to add the hamburger each time. VS code doesn't in their document- https://code.visualstudio.com/docs/getstarted/settings#_settings-editor
They just write "File > Preferences > Settings", for example. What do you think?
