### ISSUE TITLE
Feedback for "Restart a Dev Space"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-business-application-studio#141]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/1f5458361583460b83eb0e208b89b0ed.html?version=Cloud

API "/ws-manager/api/v1" cannot be found on SAP API Business Hub? Can you publish the API on https://api.sap.com/ to see more details of the API.

**Comment by Paolaufer** [comment]
Hi @offer8,
Any update on this?

**Comment by Paolaufer** [comment]
Hi @mar-hol,
Thank you for your feedback.
We are aware the API has not been published. 
Could you let us know which API details you need so that we can make sure any missing information is added to the documentation?

**Comment by mar-hol** [comment]
Hi @Paolaufer , thanks for your feedback. There are no specific requirements - but at least all available details which can be accessed through the API would help - e.g. for troubleshooting or monitoring purposes . Same as for all the available APIs on SAP API Business Hub - one place where you can explore the API. Best regards, Marco
