### ISSUE TITLE
Feedback for "Explore and Install VS Code Extensions"

### ISSUE THREAD

**Issue by Paolaufer** [SAP-docs/btp-business-application-studio#142]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/d83a580979b841c3a424e6aa50ed2483.html?q=extensions

Update the extensions icon

**Comment by ShiraManas** [comment]
Updated. Is it hard to see in this color theme, though? It's the default theme so I think we should use it, but it's kind of unclear.
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/daa8adb7947848d8af8fc62e838e830e/d83a580979b841c3a424e6aa50ed2483.html?locale=en-US&state=DRAFT

**Comment by ShiraManas** [comment]
Updated:
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/daa8adb7947848d8af8fc62e838e830e/d83a580979b841c3a424e6aa50ed2483.html?state=DRAFT
Looks better now! Thanks for sending the image.

**Comment by Paolaufer** [comment]
Yes, looks better. I would maybe still make it a bit smaller. What do you think?

**Comment by ShiraManas** [comment]
I think it looks good now. :)
