### ISSUE TITLE
Feedback for "Explore and Install VS Code Extensions"

### ISSUE THREAD

**Issue by Paolaufer** [SAP-docs/btp-business-application-studio#143]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/d83a580979b841c3a424e6aa50ed2483.html?q=extensions
there are now different sections. 
@liatbor What is the difference between DEV SPACE - INSTALLED and BROWSER - INSTALLED?

And we are no longer showing the ones installed by default like we were in the past.

**Comment by liatbor** [comment]
Hi @Paolaufer,
All our extension are installed under the dev-space extensions. I'm not sure yet what is installed under browser.

**Comment by Paolaufer** [comment]
We called it "Installed" in the documentation.
If there is a differentiation later on, we'll update the doc.
