### ISSUE TITLE
Feedback for "Importing Projects"

### ISSUE THREAD

**Issue by Paolaufer** [SAP-docs/btp-business-application-studio#144]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/2ada2be6bedd4cfc926a1347b87ebfe7.html?q=mporting

A new workspace will not open. You have to have one already open

**Comment by ShiraManas** [comment]
I see you have updated the doc to include Step 1: Make sure there is an open workspace in your dev space. If there is no open workspace...
I'll close this issue.
