### ISSUE TITLE
Feedback for "Working in the Dev Space Manager"

### ISSUE THREAD

**Issue by Paolaufer** [SAP-docs/btp-business-application-studio#145]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/ad40d52d0bea4d79baaf9626509caf33.html?q=extensions

Add a note that you must first stop the dev space before you can edit it.

**Comment by ShiraManas** [comment]
I see we have a line already in the topic: To add extentions, the dev space must be in the stopped state.
Do you want to make this into a note instead?

**Comment by Paolaufer** [comment]
Yes, I missed this phrase, maybe in a note it will catch the eye more.

**Comment by ShiraManas** [comment]
Updated: https://help.sap.com/docs/SAP%20Business%20Application%20Studio/daa8adb7947848d8af8fc62e838e830e/ad40d52d0bea4d79baaf9626509caf33.html?state=DRAFT

**Comment by Paolaufer** [comment]
I will move the note to under the first step in the procedure and change the wording from "add" to "edit".
