### ISSUE TITLE
Feedback for "Application Plans"

### ISSUE THREAD

**Issue by jklingelhoefer** [SAP-docs/btp-business-application-studio#146]
The section **Upgrading to the Standard-Edition Plan** misses IMHO information about necessary entitlement for the subaccount. This could be listed as a prerequisite in this section.

**Comment by Paolaufer** [comment]
I have added the following note:

If you don't see the standard-edition plan option in the list, make sure that there's an entitlement for SAP Business Application Studio in your subaccount. See [Configure Entitlements and Quotas for Subaccounts](https://help.sap.com/products/BTP/65de2977205c403bbc107264b8eccf4b/5ba357b4fa1e4de4b9fcc4ae771609da.html).

It will be published in the next release.

**Comment by jklingelhoefer** [comment]
https://people.sap.com/j.klingelhoefer
