### ISSUE TITLE
Feedback for "Manage Authorizations and Roles"

### ISSUE THREAD

**Issue by sundbing** [SAP-docs/btp-business-application-studio#148]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/01e69c53003c4b0a8a64310a3f08867d.html

It may be helpful to line out, that using role collection administrator is not enough to manage Business Application Studio. 
Also Developer is needed.

**Comment by Paolaufer** [comment]
Hi,
Can you please tell me as an admin, for which operation you needed the developer role?
Thanks!

**Comment by sundbing** [comment]
Hi,

Problem was, that accessing a newly created BAS was not possible after adding the admin role to the creating user.

We would have expected, that an admin role has more rights than a developer, not a purly distinct role and using Postman and similar for actions to be tanken.

So access to BAS is only possible for a User with developer role assigned, not for admin role.

**Comment by Paolaufer** [comment]
I added a note at the beginning on the topic stating that you need both roles.
It will be visible after our next release.
Thank you for your help in making our product better!
