### ISSUE TITLE
Feedback for "Connecting to External Systems"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-business-application-studio#149]
https://help.sap.com/docs/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/7e49887e6fd34182bebeca5a6841a0cc.html

the provided link "See [Developing an SAP Fiori Application Based on an SAP S/4HANA System](https://help.sap.com/viewer/584e0bcbfd4a4aff91c815cefa0bce2d/Cloud/en-US/22f3401b2e464344943f2a6abf05d092.html)" in section 4. referred in row "Service Catalog" leads to a guide which is labeled as "deprecated"
![image](https://user-images.githubusercontent.com/38477763/215570097-681f82a8-623b-411f-8897-aeab33152426.png)
Please adjust accordingly to a up-to-date guide

**Comment by ShiraManas** [comment]
Hi! You are absolutely right. Thanks for pointing this out. I will fix it right away to not link to deprecated topics.

**Comment by mar-hol** [comment]
https://people.sap.com/mar-hol
