### ISSUE TITLE
Feedback for "Working with a Trial Account"

### ISSUE THREAD

**Issue by BorisDafov** [SAP-docs/btp-business-application-studio#152]
https://help.sap.com/docs/bas/sap-business-application-studio/working-with-trial-account?q=trial%20account
I don't know how feasible it is, but it would be  good during the creation of a 90-days trial account, the user to be given the option to automatically create ( maybe limited) account on the  SAP Gateway Demo System with preconfigured destination.

**Comment by ShiraManas** [comment]
Thanks for the suggestion, Boris! Can you post it in the [SAP Continuous Influence site for SAP Business Application Studio](https://influence.sap.com/sap/ino/#campaign/2538)?
