### ISSUE TITLE
Clarification on why BAS IP Addresses should be allowed separately from general SAP BTP IP addresses

### ISSUE THREAD

**Issue by daniil-bolobonov** [SAP-docs/btp-business-application-studio#155]
### Issue description

From our perspective the necessitiy to make BAS IP addresses available separately (as per https://help.sap.com/docs/bas/sap-business-application-studio/sap-business-application-studio-availability) from general SAP BTP IP addresses (https://help.sap.com/docs/btp/sap-business-technology-platform/regions-and-api-endpoints-available-for-cloud-foundry-environment?version=Cloud) contradicts the general connectivity setup with Cloud Connector paradigm. Could please elaborate on this in the documentation?

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Architectural Overview

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/bas/sap-business-application-studio/architectural-overview?version=Cloud

**Comment by Paolaufer** [comment]
BAS has its own IP addresses because it has its own dedicated k8s clusters. BAS does not share the core infrastructure with BTP.
