### ISSUE TITLE
Cannot open the SAPUI5 Visual Editor

### ISSUE THREAD

**Issue by Zzwaaaa** [SAP-docs/btp-business-application-studio#156]
### Issue description

![image](https://github.com/SAP-docs/btp-business-application-studio/assets/145825862/8d2477db-877e-4345-a068-e10db9273a88)

### Feedback Type (Optional)

other

### Page Title on SAP Help Portal (prefilled)

Access SAP Business Application Studio from VS Code

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/bas/sap-business-application-studio/working-remotely

**Comment by ShiraManas** [comment]
I sent on information from the developers who are working to fix this issue in the upcoming weeks.
