### ISSUE TITLE
Unable to open 'X.view.xml' with the layout editor

### ISSUE THREAD

**Issue by TakingTao** [SAP-docs/btp-business-application-studio#157]
![image](https://github.com/SAP-docs/btp-business-application-studio/assets/151892714/36a93d58-14e9-4885-b263-e0be2614d96c)
![image](https://github.com/SAP-docs/btp-business-application-studio/assets/151892714/92aa4a1c-73f2-4a77-b05b-533fd6bc2d7a)

**Comment by licam** [comment]
Please report a bug in our Jira with your project attached as zip file:
https://jira.tools.sap/projects/DEVXBUGS/issues
The right component is CA-BAS-W5G.

**Comment by ShiraManas** [comment]
Hi. Since this is not a documentation issue, I'm closing the issue and encourage you to follow up by opening a JIRA ticket, as Licam described. Thanks and best wishes.
