### ISSUE TITLE
Python is missing on Runtime Version Management doc page

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAP-docs/btp-business-application-studio#158]
### Issue description

The page only discusses Java and node.js, but is missing Python.

### Feedback Type (Optional)

outdated information

### Page Title on SAP Help Portal (prefilled)

Runtime Version Management

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/bas/sap-business-application-studio/runtime-version-management

**Comment by Paolaufer** [comment]
Thank you for bringing this to our attention. I have added Python. You will see it next time the document is published.
