### ISSUE TITLE
Broken link to SAP HANA Native Application from BAS home page

### ISSUE THREAD

**Issue by Sygyzmundovych** [SAP-docs/btp-business-application-studio#159]
### Issue description

The link to [SAP HANA Native Application](https://help.sap.com/docs/r/c2b99f19e9264c4d9ae9221b22f6f589/2020_04_QRC/en-US) is broken on the home page of https://help.sap.com/docs/bas

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

SAP Business Application Studio

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/bas

**Comment by Paolaufer** [comment]
I have fixed the link and republished. Thank you!
