### ISSUE TITLE
Feedback for "What is SAP Business Application Studio"

### ISSUE THREAD

**Issue by santiagogm1995** [SAP-docs/btp-business-application-studio#16]
Hello experts!! :smile: 

I'm looking at this part of the documentation '_You can find the regions where SAP Business Application Studio is available in the **Service Catalog**. Choose the list view () to see the details._' in the section **What is SAP Business Application Studio**.

The link of **Service Catalog** is resolving with a 404 not found. It is possible that the url has changed to [link](https://discovery-center.cloud.sap/serviceCatalog/business-application-studio?region=all)?

Thank you in advance.

https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/8f46c6e6f86641cc900871c903761fd4.html?locale=en-US

**Comment by Paolaufer** [comment]
Hi @santiagogm1995,
Thank you for bringing this to our attention!
I will update the link. You will be able to see the change in the Help Portal soon.
Regards,
Pao

**Comment by santiagogm1995** [comment]
https://people.sap.com/santiagogm
