### ISSUE TITLE
Feedback for "Manage Authorizations and Roles"

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-business-application-studio#17]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/01e69c53003c4b0a8a64310a3f08867d.html

The description of the different Roles for Business Application Studio is very generic. The following descriptions:

* To allow development using SAP Business Application Studio, the developer must be assigned the Developer role.
* To allow administrator operations using SAP Business Application Studio, the relevant user must be assigned the Administrator role.
* To allow a developer to create an SAP Business Application Studio extension, the relevant user must be assigned the Extension Deployer role.

Should be explained in more detail. What are "administrator operations"? What covers "development"?

The Security Guide contains no additional details either.

**Comment by ShiraManas** [comment]
I am following up with my dev team and will get back to you soon. Thanks for your feedback!

**Comment by ShiraManas** [comment]
There is more detail about each role in the Assigning Permissions section of [Manage Authorizations and Roles](https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/01e69c53003c4b0a8a64310a3f08867d.html?locale=en-US&version=Cloud). But I have moved the description of each role to the beginning of the topic to make it more clear and have added links to topics describing the Admin role's specific capabilities. The changes will appear in our next release (about a week and a half). Thanks again for your valuable feedback!
