### ISSUE TITLE
Feedback for "What is SAP Business Application Studio"

### ISSUE THREAD

**Issue by BaerbelW** [SAP-docs/btp-business-application-studio#21]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/8f46c6e6f86641cc900871c903761fd4.html?locale=en-US

Just wondering - as the title is worded as a question - whether or not it should have a question mark at the end?

Cheers
Bärbel

**Comment by ShiraManas** [comment]
Thank you for your feedback! You are right. I am updating this now and the update will appear with the next release.

**Comment by BaerbelW** [comment]
https://people.sap.com/baerbel.winkler2
