### ISSUE TITLE
Feedback for "What is SAP Business Application Studio"

### ISSUE THREAD

**Issue by BaerbelW** [SAP-docs/btp-business-application-studio#22]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/8f46c6e6f86641cc900871c903761fd4.html?locale=en-US

The following sentence in the initial paragraph could be easier to read if broken into two sentences:
"At the heart of SAP Business Application Studio are the dev spaces, _which are like_ isolated virtual machines in the cloud containing tailored tools and preinstalled runtimes per business scenario, such as SAP Fiori, SAP S/4HANA extensions, Workflow, Mobile and more."
==> suggested reword:
"At the heart of SAP Business Application Studio are the dev spaces.  **These are comparable to** isolated virtual machines in the cloud containing tailored tools and preinstalled runtimes per business scenario, such as SAP Fiori, SAP S/4HANA extensions, Workflow, Mobile and more."

Cheers
Bärbel

**Comment by ShiraManas** [comment]
I agree with you and am updating this to:
At the heart of SAP Business Application Studio are the dev spaces. The dev spaces are comparable to isolated virtual machines in the cloud containing tailored tools and preinstalled runtimes per business scenario, such as SAP Fiori, SAP S/4HANA extensions, Workflow, Mobile and more.
Thank you for your feedback!!
