### ISSUE TITLE
Feedback for "Delete Personal Data"

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-business-application-studio#24]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/03da2fa7b94841aebe756fec24ee9456.html

5. Make sure the dev space you want to **export** is in status Running ...

Is the dev space exported before deleting or is "export" wrong here?

**Comment by ShiraManas** [comment]
Thanks for your feedback! I am checking with the dev teams and will get back to you soon.

**Comment by ShiraManas** [comment]
Yes, you are correct. I have updated the term and the updated term will appear in our next release (around a week and a half from now). Thanks!
