### ISSUE TITLE
Feedback for "SAP Fiori"

### ISSUE THREAD

**Issue by stefania-santimbrean** [SAP-docs/btp-business-application-studio#25]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/354f00cbdecf49e28084ac148a976386.html?locale=en-US&q=html5

Hello,

In the section:

```

- HTML5 Runner

Allows you to locally run HTML5 applications. Includes the HTML5 application runner and run configurations.

See Create Run Configurations for HTML5 Applications.
```

When I click on the link [Create Run Configurations for HTML5 Applications](https://help.sap.com/viewer/0e2ec06ee34742fd9054fabe09c12d35/Cloud/en-US/a72ecc1d642f4621acb795e106227a7d.html) I am routed to a page where I receive message "403: You don’t have rights to view this page.".

Could you please point me to an accessible link?

Thank you,
Stefania

**Comment by stefania-santimbrean** [comment]
If I try to navigate to **Create Run Configurations for HTML5 Applications** also from [here](https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/7188fed1e3764dbc8f71f0d8650d7b68.html?locale=en-US&q=html5) I get 403.

**Comment by ShiraManas** [comment]
You're right. Thank you very much for pointing that out. I have fixed this and the links should be visible for you now.
Can you confirm that you can access these topics?

**Comment by stefania-santimbrean** [comment]
@ShiraManas yes, I can access from both pages 💯  Thank you!

**Comment by stefania-santimbrean** [comment]
https://people.sap.com/stefania-santimbrean

**Comment by ShiraManas** [comment]
Great! Thank you again for making me aware of this issue.
