### ISSUE TITLE
Feedback for "Security Guide"

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-business-application-studio#27]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/7b2bdd5e38e64f129988b86e8e2836e3.html?locale=en-US

There is a typo in "It includes infomration on the following:" - information would be correct.

And the Security Guide has three sub-pages, but the overview page only mentions the first two.

**Comment by ShiraManas** [comment]
The typo has been fixed and will be updated in the next release (in about a week).
I have added a link to the 3rd subtopic, which will also be updated in the next release.
Thanks for the feedback!
