### ISSUE TITLE
Feedback for "Adding an Existing Project Using Git Remote": git username / email are automatically set during dev space creation

### ISSUE THREAD

**Issue by raz-korn** [SAP-docs/btp-business-application-studio#28]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/0930e56885944a2dbef1bc98ac12b4f0.html?q=username

git username / email are automatically set during dev space creation

**Comment by Paolaufer** [comment]
Hi @raz-korn,
When in the procedure does this happen? Would you like me to only add a note stating this?

**Comment by raz-korn** [comment]
Hi @Paolaufer 
Please check with Avital. AFAIK, git settings takes place as part of the dev space creation. No user interaction, i.e. the user does not provide username/email. This information is available for BAS. Perhaps this should also be mentioned: Which username / email are used by BAS.

**Comment by Paolaufer** [comment]
Hi Raz,
You were right, git credentials are automatically set. 
The document has been updated.

**Comment by raz-korn** [comment]
https://people.sap.com/raz.korn
