### ISSUE TITLE
Feedback for "Adding an Existing Project Using Git Remote": Note on branch name change

### ISSUE THREAD

**Issue by raz-korn** [SAP-docs/btp-business-application-studio#29]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/0930e56885944a2dbef1bc98ac12b4f0.html?q=username

The command "$ git branch -M main" changes the name of the current branch (ref: https://www.atlassian.com/git/tutorials/using-branches).
Therefore, the note should be "Change the name of the branch from Master to Main." instead of "The name of the branch was changed from Master to Main.".
Why changing the branch name - ref: https://github.com/github/renaming

**Comment by Paolaufer** [comment]
@raz-korn 
Thank you for bringing this up.
I think that maybe we no longer need the note. Our Git users will have encountered the name change already (it took place quite some time ago now) and new users will create a Main branch as instructed. There is no name change required.

**Comment by raz-korn** [comment]
Hi @Paolaufer 
I just run the git flow end2end (excluding step 7) and have a broader feedback:
1. The Git View provides all needed functionality. Why promote CLI?
2. When initializing the local repository it is initialized as "master". Therefore, the need to make the branch name change is still required.
3. When using the convenience button to copy the command, it also copies the "$" at the beginning, which the user than needs to manually remove.

**Comment by Paolaufer** [comment]
Hi Raz,
I believe your question was answered by DJ.
I'm closing the issue.
