### ISSUE TITLE
Feedback for "Architectural Overview"

### ISSUE THREAD

**Issue by santiagogm1995** [SAP-docs/btp-business-application-studio#32]
Hello experts!

I am trying to access the Related Links ( Manage Authorizations from CLI & Manage Authorizations from SAP BTP cockpit ) but it returns me to the home page. 

Thanks and best regards!

https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/c93afb5743a04b62afea0fe1def00062.html?locale=en-US

**Comment by Paolaufer** [comment]
HI,
Sorry about that.
Both those topics were merged into one:
Manage Authorizations and Roles - https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/01e69c53003c4b0a8a64310a3f08867d.html?version=Cloud

I will update the documentation, but in the meantime, I hope you can find what you were looking for in the link above.
If not, then please reopen the issue.
