### ISSUE TITLE
Feedback for "Build and Deploy" - Suggestion

### ISSUE THREAD

**Issue by rcaziraghi** [SAP-docs/btp-business-application-studio#34]
Hello experts!

In the "Build and Deploy" section we have only the MTA development subsection on the matter. Is it intended on remain on that way or can we expand on deploy options?

If is intended on be expanded, please let me know so that I can contribute (if possible).

Thank you very much for your time!

https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/d5e4d02d976f40feabe9b4c57443b7a5.html

**Comment by Paolaufer** [comment]
Hi,
Thank you! I would very much like to learn about your deployment options.

**Comment by rcaziraghi** [comment]
https://people.sap.com/rcaziraghi

**Comment by rcaziraghi** [comment]
Thank you @Paolaufer ! Excited to be able to contribute.
