### ISSUE TITLE
Feedback for "Service Center"

### ISSUE THREAD

**Issue by ShiraManas** [SAP-docs/btp-business-application-studio#4]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/1e8ec75c9c784b51a91c7370f269ff98.html?locale=en-US&version=Cloud

Hi,
Whenever the menucascade tag is used in DITA, the viewer adds an extra arrow at the end that wasn't there before (in place of a space?). This may be confusing for the user.

Some examples:
Service Center: Steps 1, 6a, 8a
Creating a Project from the Terminal: Step 1
Consuming SAP Services: Step 1

Thanks,
Shira

**Comment by qmacro** [comment]
This is being handled internally, thanks for raising this @ShiraManas !
