### ISSUE TITLE
Feedback for "Additional Extensions"

### ISSUE THREAD

**Issue by tpowlas3** [SAP-docs/btp-business-application-studio#5]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/7188fed1e3764dbc8f71f0d8650d7b68.html

Just wondering why there is an error at the very end of this - looks strange - see attached image

![feedback extra arrow](https://user-images.githubusercontent.com/18076299/119556592-37c9f780-bd6d-11eb-8140-6991017f2f49.png)

**Comment by qmacro** [comment]
Thanks Tammy, this does look a little odd at first but in fact it's by design, to highlight the fact that this link will take you away from the SAP Help Portal. So the arrow signifies that departure, and the arrow deliberately follows the hyperlink.
