### ISSUE TITLE
Feedback for "Terminal" - a suggestion

### ISSUE THREAD

**Issue by greg2git** [SAP-docs/btp-business-application-studio#6]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/c8b4ae95701942a5a21be4e84749f97f.html

i would add that the quickest way to arrive at the directory in the terminal is to right-click on the folder in the explorer and then select 'Open in Terminal'.

Thank you,
gm

**Comment by Paolaufer** [comment]
Hi @greg2git 👋 
Thank you for helping us improve our product.
I will update the guide accordingly. You will be able to see the updated document within a couple of days.
