### ISSUE TITLE
Feedback for "Working in the Dev Space Manager"

### ISSUE THREAD

**Issue by abul123** [SAP-docs/btp-business-application-studio#78]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/ad40d52d0bea4d79baaf9626509caf33.html

I found that the alt attribute of the <image> tag is missing for the image tags of this page in the documentation. It will be helpful for the reader to find **alt** attribute if the network is slow or has some other issue. 

can we add **alt** attribute for all image tags of this page in the documentation? 
example : 
<img class="inline" id="loioad40d52d0bea4d79baaf9626509caf33__image_g1b_1vs_fnb" alt="Edit Icon/Button" src="https://help.sap.com/doc/9d1db9835307451daa8c930fbd9ab264/Cloud/en-US/loio7f87f6e3ebec4295b534881f8b186ee1_HiRes.jpg">

**Comment by Paolaufer** [comment]
I've added attributes to this page. Am going over the others to fix this as well.
THank you.
