### ISSUE TITLE
Feedback for "Explore and Install VS Code Extensions"

### ISSUE THREAD

**Issue by abul123** [SAP-docs/btp-business-application-studio#79]
https://help.sap.com/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/d83a580979b841c3a424e6aa50ed2483.html

The image tag of this page is missing the **alt** attribute. I am seeing similar issues on the other pages of the btp-business-application documentation.

**Comment by Paolaufer** [comment]
Hi,
I added the tag to this page. Will scan through others to correct there as well.
Thank you for bringing this to my attention.
