### ISSUE TITLE
Feedback for "What is SAP Business Application Studio"

### ISSUE THREAD

**Issue by ajmaradiaga** [SAP-docs/btp-business-application-studio#9]
https://help.sap.com/webcomponents/products/SAP%20Business%20Application%20Studio/9d1db9835307451daa8c930fbd9ab264/8f46c6e6f86641cc900871c903761fd4.html?locale=en-US&version=Cloud&q=Theia

In the documentation, when explaining what is SAP Business Application Studio, there is no mention that it is based on the open source Eclipse Theia. Shouldn't there be a mention of it?

Reference: https://blogs.sap.com/2020/07/15/sap-business-application-studio-openness/

**Comment by Paolaufer** [comment]
Thanks for your feedback.
I'll check internally and will send an update soon.

**Comment by ShiraManas** [comment]
I have added this to the documentation and it will appear in our upcoming release: 
SAP Business Application Studio is based on an open source IDE, Elipse Theia, which embraces the Microsoft Visual Studio Code experience.

Thank you for your valuable feedback!

**Comment by ajmaradiaga** [comment]
https://people.sap.com/ajmaradiaga

**Comment by ajmaradiaga** [comment]
@ShiraManas not sure if the doc bot worked as expected... I was checking my community profile today and a badge was not assigned to my profile :-(.

**Comment by ShiraManas** [comment]
Hi! I will look into this and make sure you get the badge. Thanks for letting me know!

**Comment by Paolaufer** [comment]
@je-hal, could you please help us figure out why ajmaradiaga did not get a badge?

**Comment by qmacro** [comment]
Please accept my apologies @ajmaradiaga, this was completely my fault - I'll get the process fixed. In the meantime, I've kicked off the mechanism for you to get your badge.
